# Site settings
title: Fernando Bastos
description: Fernando Bastos Portfolio
keywords: professor, estatística, R, matemática
author: IMG_FSB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fsbmat-ufv.github.io/#" # the base hostname & protocol for your site
permalink: /:collection/:path/
# Google services
google_analytics: "UA-164763641-3"