---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

<style type="text/css">																									
table.table-style-two {																									
font-family: verdana, arial, sans-serif;																									
font-size: 11px;																									
color: #333333;																									
border-width: 1px;																									
border-color: #3A3A3A;																									
border-collapse: collapse;																									
}																									
table.table-style-two th {																									
border-width: 1px;																									
padding: 8px;																									
border-style: solid;																									
border-color: #517994;																									
background-color: #B2CFD8;																									
}																									
																									
table.table-style-two tr:hover td {																									
background-color: #DFEBF1;																									
}																									
																									
table.table-style-two td {																									
border-width: 1px;																									
padding: 8px;																									
border-style: solid;																									
border-color: #517994;																									
background-color: #ffffff;																									
}

.floatLeft { width: 50%; float: left; }
.floatRight {width: 50%; float: right; }
.container { overflow: hidden; }
</style>
<!--Tabelas de Cursos e Webinarios-->
<div class="container">
<div class="floatLeft">
<!-- Table goes in the document BODY -->
<!-- Tabela 1 (Cursos) -->
<!--Substituir A partir daqui-->
<table class="table-style-two">																									
<thead>																									
<tr>	<th colspan="4">	<center>	Cursos	</center>	</th>	</tr>																			
<tr>	<th>	<center>	Quantidade	</center>	</th>	<th>	<center>	Descrição	</center>	</th>	<th>	<center>		Links				</center>	</th>	<th>	<center>	Observações	</center>	</th>	</tr>
</thead>																									
<tbody>																									
<tr>	<td>	<center>	1	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	http://veduca.org/	" target="_blank">	Veduca	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	2	</center>	</th>	<td>	<center>	Ciência de Dados	</center>	</th>	<td>	<center>	<a href="	https://www.datascienceacademy.com.br/	" target="_blank">	Data Science Academy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	3	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://medium.com/lambda-school-blog	" target="_blank">	Lambda	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	4	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.codeavengers.com/	" target="_blank">	Code Avenger	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	5	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.w3schools.com/	" target="_blank">	W3Schools	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	6	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.udacity.com/	" target="_blank">	Udacity	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	7	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://www.udemy.com/	" target="_blank">	Udemy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	8	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.codecademy.com/catalog/all	" target="_blank">	Code Academy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	9	</center>	</th>	<td>	<center>	Maple	</center>	</th>	<td>	<center>	<a href="	https://www.maplesoft.com/support/LATAM/Latin_American_Resource_Centre_PT.aspx?p=TC-5976	" target="_blank">	Maple	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	10	</center>	</th>	<td>	<center>	Wolfram Cloud	</center>	</th>	<td>	<center>	<a href="	https://lab.open.wolframcloud.com/app/	" target="_blank">	Wolfram Alpha	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	11	</center>	</th>	<td>	<center>	Inglês	</center>	</th>	<td>	<center>	<a href="	http://www.mairovergara.com/	" target="_blank">	Mairo Vergara	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	12	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://www.coursera.org/	" target="_blank">	Coursera	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	13	</center>	</th>	<td>	<center>	Inglês	</center>	</th>	<td>	<center>	<a href="	http://isf.mec.gov.br/	" target="_blank">	Idiomas sem Fronteiras	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	14	</center>	</th>	<td>	<center>	Estatística	</center>	</th>	<td>	<center>	<a href="	https://comunidadeestatistica.landen.co/	" target="_blank">	Estatidados	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	15	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://financial-risk-academy.teachable.com/	" target="_blank">	Financial Risk Academy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	16	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://github.com/fsbmat-ufv/CursosOnline/raw/master/IF_Pernambuco.pdf	" target="_blank">	Trilha de Cursos EAD	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	17	</center>	</th>	<td>	<center>	Estatística	</center>	</th>	<td>	<center>	<a href="	https://www.ufrgs.br/probabilidade-estatistica/	" target="_blank">	Estatística - UFRGS	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	18	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	19	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	20	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	21	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	22	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	23	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	24	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	25	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	26	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	27	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	28	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	29	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	30	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	31	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	32	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	33	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	34	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	35	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	36	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	37	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	38	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	39	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	40	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	41	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	42	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	43	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	44	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	45	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	46	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	47	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	48	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	49	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	50	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	51	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	52	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	53	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	54	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	55	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	56	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	57	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	58	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	59	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	60	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	61	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	62	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	63	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	64	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	65	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	66	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	67	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	68	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	69	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	70	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	71	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	72	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	73	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	74	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	75	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	76	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	77	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	78	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	79	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	80	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	81	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	82	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	83	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	84	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	85	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	86	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	87	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	88	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	89	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	90	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	91	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	92	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	93	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	94	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	95	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	96	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	97	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	98	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	99	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	100	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
</tbody>																									
</table>
<!--Substituir ate a linha anterior-->
</div>

<div class="floatRight">
<tr><!-- Table goes in the document BODY -->																									<!-- Tabela 2 (Webinários) -->
<!--Substituir A partir daqui-->
<table class="table-style-two">																									
<thead>																									
<tr>	<th colspan="4">	<center>	Webinários	</center>	</th>	</tr>																			
<tr>	<th>	<center>	Quantidade	</center>	</th>	<th>	<center>	Descrição	</center>	</th>	<th>	<center>		Links				</center>	</th>	<th>	<center>	Observações	</center>	</th>	</tr>
</thead>																									
<tbody>																									
<tr>	<td>	<center>	1	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	http://veduca.org/	" target="_blank">	Veduca	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	2	</center>	</th>	<td>	<center>	Ciência de Dados	</center>	</th>	<td>	<center>	<a href="	https://www.datascienceacademy.com.br/	" target="_blank">	Data Science Academy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	3	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://medium.com/lambda-school-blog	" target="_blank">	Lambda	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	4	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.codeavengers.com/	" target="_blank">	Code Avenger	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	5	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.w3schools.com/	" target="_blank">	W3Schools	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	6	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.udacity.com/	" target="_blank">	Udacity	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	7	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://www.udemy.com/	" target="_blank">	Udemy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	8	</center>	</th>	<td>	<center>	Programação	</center>	</th>	<td>	<center>	<a href="	https://www.codecademy.com/catalog/all	" target="_blank">	Code Academy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	9	</center>	</th>	<td>	<center>	Maple	</center>	</th>	<td>	<center>	<a href="	https://www.maplesoft.com/support/LATAM/Latin_American_Resource_Centre_PT.aspx?p=TC-5976	" target="_blank">	Maple	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	10	</center>	</th>	<td>	<center>	Wolfram Cloud	</center>	</th>	<td>	<center>	<a href="	https://lab.open.wolframcloud.com/app/	" target="_blank">	Wolfram Alpha	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	11	</center>	</th>	<td>	<center>	Inglês	</center>	</th>	<td>	<center>	<a href="	http://www.mairovergara.com/	" target="_blank">	Mairo Vergara	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	12	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://www.coursera.org/	" target="_blank">	Coursera	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	13	</center>	</th>	<td>	<center>	Inglês	</center>	</th>	<td>	<center>	<a href="	http://isf.mec.gov.br/	" target="_blank">	Idiomas sem Fronteiras	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	14	</center>	</th>	<td>	<center>	Estatística	</center>	</th>	<td>	<center>	<a href="	https://comunidadeestatistica.landen.co/	" target="_blank">	Estatidados	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	15	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://financial-risk-academy.teachable.com/	" target="_blank">	Financial Risk Academy	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	16	</center>	</th>	<td>	<center>	Cursos Diversos	</center>	</th>	<td>	<center>	<a href="	https://github.com/fsbmat-ufv/CursosOnline/raw/master/IF_Pernambuco.pdf	" target="_blank">	Trilha de Cursos EAD	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	17	</center>	</th>	<td>	<center>	Estatística	</center>	</th>	<td>	<center>	<a href="	https://www.ufrgs.br/probabilidade-estatistica/	" target="_blank">	Estatística - UFRGS	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	18	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	19	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	20	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	21	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	22	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	23	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	24	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	25	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	26	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	27	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	28	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	29	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	30	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	31	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	32	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	33	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	34	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	35	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	36	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	37	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	38	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	39	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	40	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	41	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	42	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	43	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	44	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	45	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	46	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	47	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	48	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	49	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	50	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	51	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	52	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	53	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	54	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	55	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	56	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	57	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	58	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	59	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	60	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	61	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	62	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	63	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	64	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	65	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	66	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	67	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	68	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	69	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	70	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	71	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	72	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	73	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	74	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	75	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	76	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	77	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	78	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	79	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	80	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	81	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	82	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	83	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	84	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	85	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	86	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	87	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	88	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	89	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	90	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	91	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	92	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	93	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	94	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	95	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	96	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	97	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	98	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	99	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	100	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
</tbody>																									
</table>
<!--Substituir ate a linha anterior-->
</div>
</div>																																																								
																				
																		


<br></br>

<br></br>








<!--Tabelas de Aplicativos e Canais-->
<div class="container">
<div class="floatLeft">
<!-- Table goes in the document BODY -->
<!-- Tabela 1 (Aplicativos) -->
<!--Substituir A partir daqui-->
<table class="table-style-two">																									
<thead>																									
<tr>	<th colspan="4">	<center>	Aplicativos	</center>	</th>	</tr>																			
<tr>	<th>	<center>	Quantidade	</center>	</th>	<th>	<center>	Descrição	</center>	</th>	<th>	<center>		Links				</center>	</th>	<th>	<center>	Observações	</center>	</th>	</tr>
</thead>																									
<tbody>																									
<tr>	<td>	<center>	1	</center>	</th>	<td>	<center>	Aplicativo de Matemática Dinâmica	</center>	</th>	<td>	<center>	<a href="	https://www.geogebra.org/?lang=pt	" target="_blank">	Geogebra	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	2	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	3	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	4	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	5	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	6	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	7	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	8	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	9	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	10	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	11	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	12	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	13	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	14	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	15	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	16	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	17	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	18	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	19	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	20	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	21	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	22	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	23	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	24	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	25	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	26	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	27	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	28	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	29	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	30	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	31	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	32	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	33	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	34	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	35	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	36	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	37	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	38	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	39	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	40	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	41	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	42	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	43	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	44	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	45	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	46	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	47	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	48	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	49	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	50	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	51	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	52	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	53	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	54	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	55	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	56	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	57	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	58	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	59	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	60	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	61	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	62	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	63	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	64	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	65	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	66	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	67	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	68	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	69	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	70	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	71	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	72	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	73	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	74	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	75	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	76	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	77	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	78	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	79	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	80	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	81	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	82	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	83	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	84	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	85	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	86	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	87	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	88	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	89	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	90	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	91	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	92	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	93	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	94	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	95	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	96	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	97	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	98	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	99	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	100	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
</tbody>																									
</table>																									
<!--Substituir ate a linha anterior-->
</div>

<div class="floatRight">
<tr><!-- Table goes in the document BODY -->																									<!-- Tabela 4 (Canais) -->
<!--Substituir A partir daqui-->
<table class="table-style-two">																									
<thead>																									
<tr>	<th colspan="4">	<center>	Canais	</center>	</th>	</tr>																			
<tr>	<th>	<center>	Quantidade	</center>	</th>	<th>	<center>	Descrição	</center>	</th>	<th>	<center>		Links				</center>	</th>	<th>	<center>	Observações	</center>	</th>	</tr>
</thead>																									
<tbody>																									
<tr>	<td>	<center>	1	</center>	</th>	<td>	<center>	Assuntos de Estatística	</center>	</th>	<td>	<center>	<a href="	https://www.youtube.com/channel/UC4jROkPjTvnXRkuo2GAwKXw	" target="_blank">	Estatidados	</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	2	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	3	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	4	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	5	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	6	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	7	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	8	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	9	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	10	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	11	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	12	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	13	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	14	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	15	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	16	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	17	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	18	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	19	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	20	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	21	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	22	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	23	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	24	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	25	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	26	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	27	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	28	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	29	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	30	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	31	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	32	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	33	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	34	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	35	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	36	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	37	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	38	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	39	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	40	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	41	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	42	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	43	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	44	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	45	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	46	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	47	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	48	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	49	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	50	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	51	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	52	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	53	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	54	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	55	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	56	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	57	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	58	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	59	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	60	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	61	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	62	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	63	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	64	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	65	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	66	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	67	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	68	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	69	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	70	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	71	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	72	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	73	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	74	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	75	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	76	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	77	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	78	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	79	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	80	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	81	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	82	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	83	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	84	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	85	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	86	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	87	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	88	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	89	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	90	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	91	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	92	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	93	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	94	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	95	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	96	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	97	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	98	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	99	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
<tr>	<td>	<center>	100	</center>	</th>	<td>	<center>		</center>	</th>	<td>	<center>	<a href="		" target="_blank">		</a>	</center>	</th>	<td>	<center>		</center>	</th>	</tr>
</tbody>																									
</table>																									
<!--Substituir ate a linha anterior-->
</div>
</div>	
